# https://docs.pytest.org/en/latest/reference.html#ini-options-ref

[pytest]
python_classes =
    *TestCase
    Test*
testpaths =
    loopstr/apps
addopts =
    --ds=config.settings
    --maxfail=2
    --durations=5
    -rfsExX
    --reuse-db
